services:
  - type: web
    name: car-rental-website
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --chdir backend --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production
